/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vsystem.view;

import br.com.vsystem.model.UsuarioModel;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author NoteBook
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    
    public UsuarioModel usuariologado;
    
    public frmMenu() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon("src/imagens/o-cenario-da-producao-de-vestuario-e-o-papel-do-brasil-no-setor.x16427.jpeg");

        Image image = icon.getImage();
        painel_desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_clientes = new javax.swing.JMenu();
        item_menu_controleClientes = new javax.swing.JMenuItem();
        menu_funcionarios = new javax.swing.JMenu();
        item_menu_controleFuncionarios = new javax.swing.JMenuItem();
        menu_fornecedores = new javax.swing.JMenu();
        item_menu_controleFornecedores = new javax.swing.JMenuItem();
        menu_produtos = new javax.swing.JMenu();
        item_menu_controleEstoque = new javax.swing.JMenuItem();
        item_menu_consultaProdutos = new javax.swing.JMenuItem();
        menu_vendas = new javax.swing.JMenu();
        item_menu_abrirPdv = new javax.swing.JMenuItem();
        item_menu_posicaoDia = new javax.swing.JMenuItem();
        item_menu_historicoVendas = new javax.swing.JMenuItem();
        menu_config = new javax.swing.JMenu();
        item_menu_trocarUsuario = new javax.swing.JMenuItem();
        menu_relatorios = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout painel_desktopLayout = new javax.swing.GroupLayout(painel_desktop);
        painel_desktop.setLayout(painel_desktopLayout);
        painel_desktopLayout.setHorizontalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        painel_desktopLayout.setVerticalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(80, 223, 152));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cloakroom_52px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 91, 91));
        jLabel2.setText("GOMES");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(91, 91, 91));
        jLabel3.setText("VESTUARIO");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 91, 91));
        jLabel4.setText("VR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Alarm Clock_48px.png"))); // NOI18N
        jLabel25.setText("Relogio:");

        lblusuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 255));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel26.setText("Usuário Logado: ");

        lblhora.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblhora.setForeground(new java.awt.Color(0, 0, 255));

        menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        menu_clientes.setText("Clientes");

        item_menu_controleClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        item_menu_controleClientes.setText("Controle de clientes");
        item_menu_controleClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_menu_controleClientesMouseClicked(evt);
            }
        });
        item_menu_controleClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_controleClientesActionPerformed(evt);
            }
        });
        menu_clientes.add(item_menu_controleClientes);

        jMenuBar1.add(menu_clientes);

        menu_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        menu_funcionarios.setText("Funcionários");

        item_menu_controleFuncionarios.setText("Controle de funcionários");
        item_menu_controleFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_controleFuncionariosActionPerformed(evt);
            }
        });
        menu_funcionarios.add(item_menu_controleFuncionarios);

        jMenuBar1.add(menu_funcionarios);

        menu_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        menu_fornecedores.setText("Fornecedores");

        item_menu_controleFornecedores.setText("Controle de fornecedores");
        item_menu_controleFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_controleFornecedoresActionPerformed(evt);
            }
        });
        menu_fornecedores.add(item_menu_controleFornecedores);

        jMenuBar1.add(menu_fornecedores);

        menu_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        menu_produtos.setText("Produtos");

        item_menu_controleEstoque.setText("Controle de estoque");
        item_menu_controleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_controleEstoqueActionPerformed(evt);
            }
        });
        menu_produtos.add(item_menu_controleEstoque);

        item_menu_consultaProdutos.setText("Consulta de produtos");
        item_menu_consultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_consultaProdutosActionPerformed(evt);
            }
        });
        menu_produtos.add(item_menu_consultaProdutos);

        jMenuBar1.add(menu_produtos);

        menu_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        menu_vendas.setText("Vendas");

        item_menu_abrirPdv.setText("Abrir PDV");
        item_menu_abrirPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_abrirPdvActionPerformed(evt);
            }
        });
        menu_vendas.add(item_menu_abrirPdv);

        item_menu_posicaoDia.setText("Posição do dia");
        item_menu_posicaoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_posicaoDiaActionPerformed(evt);
            }
        });
        menu_vendas.add(item_menu_posicaoDia);

        item_menu_historicoVendas.setText("Histórico de vendas");
        item_menu_historicoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_historicoVendasActionPerformed(evt);
            }
        });
        menu_vendas.add(item_menu_historicoVendas);

        jMenuBar1.add(menu_vendas);

        menu_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes.png"))); // NOI18N
        menu_config.setText("Configurações");

        item_menu_trocarUsuario.setText("Trocar de usuário");
        item_menu_trocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_menu_trocarUsuarioActionPerformed(evt);
            }
        });
        menu_config.add(item_menu_trocarUsuario);

        jMenuBar1.add(menu_config);

        menu_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_report_48px.png"))); // NOI18N
        menu_relatorios.setText("Relatorios");
        jMenuBar1.add(menu_relatorios);

        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_desktop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblusuario.setText(usuariologado.getNome());
        
        if(usuariologado.getNievel_acesso().equals("2")){
            menu_funcionarios.setEnabled(false);
            menu_fornecedores.setEnabled(false);
            menu_produtos.setEnabled(false);
            menu_relatorios.setEnabled(false);
            
            item_menu_posicaoDia.setEnabled(false);
            item_menu_historicoVendas.setEnabled(false);
            
        }
            
      
        Timer timer = new Timer(1000, new hora()) ;
        timer.start();
      
      
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void item_menu_controleClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_menu_controleClientesMouseClicked
                
    }//GEN-LAST:event_item_menu_controleClientesMouseClicked

    private void item_menu_controleClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_controleClientesActionPerformed
        frmCliente cliente = new frmCliente();
                
        cliente.setVisible(true);
    }//GEN-LAST:event_item_menu_controleClientesActionPerformed

    private void item_menu_abrirPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_abrirPdvActionPerformed
        frmVendas vendas = new frmVendas();
        vendas.vendedor = usuariologado;
        vendas.setVisible(true);
    }//GEN-LAST:event_item_menu_abrirPdvActionPerformed

    private void item_menu_controleFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_controleFuncionariosActionPerformed
         frmUsuario usuario = new frmUsuario();
                
         usuario.setVisible(true);
    }//GEN-LAST:event_item_menu_controleFuncionariosActionPerformed

    private void item_menu_controleFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_controleFornecedoresActionPerformed
        frmFornecedor fornecedor = new frmFornecedor();
        fornecedor.setVisible(true);
    }//GEN-LAST:event_item_menu_controleFornecedoresActionPerformed

    private void item_menu_consultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_consultaProdutosActionPerformed
        frmProduto produto = new frmProduto();
        produto.setVisible(true);
    }//GEN-LAST:event_item_menu_consultaProdutosActionPerformed

    private void item_menu_historicoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_historicoVendasActionPerformed
        frmHistorico historico = new frmHistorico();
        historico.setVisible(true);
                
    }//GEN-LAST:event_item_menu_historicoVendasActionPerformed

    private void item_menu_trocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_trocarUsuarioActionPerformed
       frmLogin login = new frmLogin();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_item_menu_trocarUsuarioActionPerformed

    private void item_menu_controleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_controleEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_menu_controleEstoqueActionPerformed

    private void item_menu_posicaoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_menu_posicaoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_menu_posicaoDiaActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        Object[] options = { "Sim", "Não" };
        switch (JOptionPane.showOptionDialog(null, "Deseja fechar o sistema?", "Confirmação", JOptionPane.WARNING_MESSAGE, JOptionPane.WARNING_MESSAGE, null, options, options[0])) {
            case 0:
                this.dispose();
                break;
            case 1:
                break;
        }
            
    }//GEN-LAST:event_menu_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_menu_abrirPdv;
    private javax.swing.JMenuItem item_menu_consultaProdutos;
    private javax.swing.JMenuItem item_menu_controleClientes;
    private javax.swing.JMenuItem item_menu_controleEstoque;
    private javax.swing.JMenuItem item_menu_controleFornecedores;
    private javax.swing.JMenuItem item_menu_controleFuncionarios;
    private javax.swing.JMenuItem item_menu_historicoVendas;
    private javax.swing.JMenuItem item_menu_posicaoDia;
    private javax.swing.JMenuItem item_menu_trocarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenu menu_clientes;
    private javax.swing.JMenu menu_config;
    private javax.swing.JMenu menu_fornecedores;
    private javax.swing.JMenu menu_funcionarios;
    private javax.swing.JMenu menu_produtos;
    private javax.swing.JMenu menu_relatorios;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_vendas;
    private javax.swing.JDesktopPane painel_desktop;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener{
@Override
public void actionPerformed(ActionEvent e ){
Calendar now = Calendar.getInstance();
lblhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
}
}

}


